package postgres

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"

	"github.com/makifbaysal/tasktrooper/server/internal/domain"
	"github.com/makifbaysal/tasktrooper/server/internal/port"
)

// LegacyModelSource reads the tables the project model replaced —
// repository_dependencies (migration 134) and repository_profile_sections
// (migration 086, sub_project_path added in 119) — so the one-time backfill
// can carry the human's earlier settings forward as overrides. Read-only:
// nothing here writes to either table, which both stay in place only so this
// adapter (and the migration's own down file) can still read them.
type LegacyModelSource struct {
	pool *DB
}

func NewLegacyModelSource(pool *DB) *LegacyModelSource {
	return &LegacyModelSource{pool: pool}
}

var _ port.LegacyModelSource = (*LegacyModelSource)(nil)

func (s *LegacyModelSource) ListLegacyDependencies(ctx context.Context, repositoryID uuid.UUID) ([]domain.LegacyDependency, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, repository_id, target_kind, target_repository_id, target_sub_project_path,
			database_label, database_engine, database_env, database_host, database_port, database_name, note
		FROM repository_dependencies
		WHERE repository_id = $1
		ORDER BY created_at`, repositoryID)
	if err != nil {
		return nil, fmt.Errorf("list legacy dependencies: %w", err)
	}
	defer rows.Close()

	var out []domain.LegacyDependency
	for rows.Next() {
		var d domain.LegacyDependency
		if err := rows.Scan(&d.ID, &d.RepositoryID, &d.TargetKind, &d.TargetRepositoryID, &d.TargetSubProjectPath,
			&d.DatabaseLabel, &d.DatabaseEngine, &d.DatabaseEnv, &d.DatabaseHost, &d.DatabasePort, &d.DatabaseName, &d.Note); err != nil {
			return nil, fmt.Errorf("scan legacy dependency: %w", err)
		}
		out = append(out, d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list legacy dependencies: %w", err)
	}
	return out, nil
}

// ListLegacyAgentSections reads only origin = 'agent' rows: the derived half
// of the old profile is regenerated by the scan itself and must never
// resurface as a note.
func (s *LegacyModelSource) ListLegacyAgentSections(ctx context.Context, repositoryID uuid.UUID) ([]domain.LegacyAgentSection, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT section, body_md, evidence, source_commit, sub_project_path
		FROM repository_profile_sections
		WHERE repository_id = $1 AND origin = 'agent'
		ORDER BY section`, repositoryID)
	if err != nil {
		return nil, fmt.Errorf("list legacy agent sections: %w", err)
	}
	defer rows.Close()

	var out []domain.LegacyAgentSection
	for rows.Next() {
		var sec domain.LegacyAgentSection
		var evidence []byte
		if err := rows.Scan(&sec.Section, &sec.BodyMD, &evidence, &sec.SourceCommit, &sec.SubProjectPath); err != nil {
			return nil, fmt.Errorf("scan legacy agent section: %w", err)
		}
		if len(evidence) > 0 {
			if err := json.Unmarshal(evidence, &sec.Evidence); err != nil {
				return nil, fmt.Errorf("unmarshal legacy section evidence: %w", err)
			}
		}
		out = append(out, sec)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list legacy agent sections: %w", err)
	}
	return out, nil
}
