package indexer_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/makifbaysal/tasktrooper/server/internal/application/indexer"
	"github.com/stretchr/testify/suite"
)

type WalkSuite struct {
	suite.Suite
}

func (s *WalkSuite) TestWalkIndexableFilesFiltersExtensions() {
	paths, err := indexer.WalkIndexableFiles(mapperFixtureRoot(), indexer.IndexWalkOptions{})
	s.Require().NoError(err)
	s.Contains(paths, "pkg/main.go")
	s.Contains(paths, "web/app.ts")
	s.Contains(paths, "scripts/run.py")
	s.NotContains(paths, "readme.md")
}

func (s *WalkSuite) TestIsIndexablePath() {
	s.True(indexer.IsIndexablePath("service.go"))
	s.True(indexer.IsIndexablePath("app.tsx"))
	s.False(indexer.IsIndexablePath("readme.md"))
}

func writeTree(s *WalkSuite, root string, files map[string]string) {
	for rel, body := range files {
		full := filepath.Join(root, filepath.FromSlash(rel))
		s.Require().NoError(os.MkdirAll(filepath.Dir(full), 0o755))
		s.Require().NoError(os.WriteFile(full, []byte(body), 0o644))
	}
}

func (s *WalkSuite) generatedTree() string {
	root := s.T().TempDir()
	writeTree(s, root, map[string]string{
		"pkg/real.go":        "package pkg\n",
		"pkg/latest.go":      "package pkg\n",
		"pkg/store_mock.go":  "package pkg\n",
		"mocks/store.go":     "package mocks\n",
		"pkg/mock_thing.go":  "package pkg\n",
		"pkg/header.go":      "// Code generated by mockery v2.43.0. DO NOT EDIT.\n\npackage pkg\n",
		"pkg/late_marker.go": "package pkg\n" + string(make([]byte, 2048)) + "\n// Code generated by x. DO NOT EDIT.\n",
		"legacy/skipme.go":   "package legacy\n",
		".tasktrooperignore": "# comment\nlegacy\n",
	})
	return root
}

func (s *WalkSuite) TestWalkDropsGeneratedAndMocksByDefault() {
	paths, err := indexer.WalkIndexableFiles(s.generatedTree(), indexer.IndexWalkOptions{})
	s.Require().NoError(err)
	s.ElementsMatch([]string{"pkg/real.go", "pkg/latest.go", "pkg/late_marker.go"}, paths)
}

func (s *WalkSuite) TestWalkIncludeGeneratedKeepsThemButStillHonoursIgnoreFile() {
	paths, err := indexer.WalkIndexableFiles(s.generatedTree(), indexer.IndexWalkOptions{IncludeGenerated: true})
	s.Require().NoError(err)
	s.ElementsMatch([]string{
		"pkg/real.go", "pkg/latest.go", "pkg/store_mock.go", "mocks/store.go",
		"pkg/mock_thing.go", "pkg/header.go", "pkg/late_marker.go",
	}, paths)
}

func (s *WalkSuite) TestExcludedFileIsReportedRemoved() {
	root := s.generatedTree()
	stored := map[string]string{"pkg/mock_thing.go": mustHash(root, "pkg/mock_thing.go")}
	paths, err := indexer.WalkIndexableFiles(root, indexer.IndexWalkOptions{})
	s.Require().NoError(err)
	changes := indexer.DetectChangedFiles(root, paths, stored)
	s.Equal([]string{"pkg/mock_thing.go"}, changes.Removed)
}

func (s *WalkSuite) TestIsGeneratedOrMockPath() {
	cases := map[string]bool{
		"mocks/store.go": true, "internal/mock/x.go": true, "src/__mocks__/api.ts": true,
		"gen/generated/x.go": true, "src/__generated__/types.ts": true,
		"pkg/mock_store.go": true, "web/mock-api.ts": true, "api/zz_generated.deepcopy.go": true,
		"pkg/store_mock.go": true, "web/store.mock.ts": true, "web/api-mocks.ts": true,
		"web/MockStore.ts": true, "api/x.pb.go": true, "api/x_pb2.py": true, "api/x_pb2_grpc.py": true,
		"api/x.pb.ts": true, "a/x_gen.go": true, "a/x.gen.go": true, "a/x.gen.ts": true,
		"dist/app.min.js": true, "src/schema.generated.ts": true,
		"pkg/latest.go": false, "pkg/contest.go": false, "mockingbird/app.ts": false,
		"pkg/service.go": false, "web/Mockingbird.ts": false, "pkg/mockery.go": false,
		"gen/mocksmith/x.go": false,
	}
	for rel, want := range cases {
		s.Equal(want, indexer.IsGeneratedOrMockPath(rel), rel)
	}
}

func (s *WalkSuite) TestHasGeneratedMarker() {
	cases := map[string]bool{
		"// Code generated by mockery v2.43.0. DO NOT EDIT.\npackage x\n":        true,
		"# Generated by the protocol buffer compiler.  DO NOT EDIT!\nimport x\n": true,
		"/**\n * @generated\n */\nexport {}\n":                                   true,
		"// @generated by tool\n":                                                true,
		"package x\n\nfunc generated() { /* do not edit */ }\n":                  false,
		"package x\n\nvar generatedAt = 1\n":                                     false,
		"":                                                                       false,
	}
	for head, want := range cases {
		s.Equal(want, indexer.HasGeneratedMarker([]byte(head)), head)
	}
}

func TestWalkSuite(t *testing.T) {
	suite.Run(t, new(WalkSuite))
}
