// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/makifbaysal/tasktrooper/server/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// LocalCodeIndex is an autogenerated mock type for the LocalCodeIndex type
type LocalCodeIndex struct {
	mock.Mock
}

// Attach provides a mock function with given fields: ctx, ref, chat
func (_m *LocalCodeIndex) Attach(ctx context.Context, ref port.LocalIndexRef, chat port.LLMClient) (port.LocalIndexAttachment, error) {
	ret := _m.Called(ctx, ref, chat)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 port.LocalIndexAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.LocalIndexRef, port.LLMClient) (port.LocalIndexAttachment, error)); ok {
		return rf(ctx, ref, chat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.LocalIndexRef, port.LLMClient) port.LocalIndexAttachment); ok {
		r0 = rf(ctx, ref, chat)
	} else {
		r0 = ret.Get(0).(port.LocalIndexAttachment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.LocalIndexRef, port.LLMClient) error); ok {
		r1 = rf(ctx, ref, chat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ensure provides a mock function with given fields: ctx, req, progress
func (_m *LocalCodeIndex) Ensure(ctx context.Context, req port.LocalIndexEnsure, progress func(port.LocalIndexProgress)) (port.LocalIndexState, error) {
	ret := _m.Called(ctx, req, progress)

	if len(ret) == 0 {
		panic("no return value specified for Ensure")
	}

	var r0 port.LocalIndexState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.LocalIndexEnsure, func(port.LocalIndexProgress)) (port.LocalIndexState, error)); ok {
		return rf(ctx, req, progress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.LocalIndexEnsure, func(port.LocalIndexProgress)) port.LocalIndexState); ok {
		r0 = rf(ctx, req, progress)
	} else {
		r0 = ret.Get(0).(port.LocalIndexState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.LocalIndexEnsure, func(port.LocalIndexProgress)) error); ok {
		r1 = rf(ctx, req, progress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, query
func (_m *LocalCodeIndex) Search(ctx context.Context, query port.LocalIndexQuery) (port.LocalIndexSearchResult, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 port.LocalIndexSearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.LocalIndexQuery) (port.LocalIndexSearchResult, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.LocalIndexQuery) port.LocalIndexSearchResult); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(port.LocalIndexSearchResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.LocalIndexQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLocalCodeIndex creates a new instance of LocalCodeIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalCodeIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalCodeIndex {
	mock := &LocalCodeIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
