// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MCPTokenSource is an autogenerated mock type for the MCPTokenSource type
type MCPTokenSource struct {
	mock.Mock
}

// MCPAccessToken provides a mock function with given fields: ctx, serverID, rejected
func (_m *MCPTokenSource) MCPAccessToken(ctx context.Context, serverID string, rejected string) (string, error) {
	ret := _m.Called(ctx, serverID, rejected)

	if len(ret) == 0 {
		panic("no return value specified for MCPAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, serverID, rejected)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, serverID, rejected)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, serverID, rejected)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMCPTokenSource creates a new instance of MCPTokenSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMCPTokenSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MCPTokenSource {
	mock := &MCPTokenSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
