// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/makifbaysal/tasktrooper/server/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MCPOAuthProvider is an autogenerated mock type for the MCPOAuthProvider type
type MCPOAuthProvider struct {
	mock.Mock
}

// Discover provides a mock function with given fields: ctx, serverURL
func (_m *MCPOAuthProvider) Discover(ctx context.Context, serverURL string) (domain.MCPOAuthMetadata, error) {
	ret := _m.Called(ctx, serverURL)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 domain.MCPOAuthMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MCPOAuthMetadata, error)); ok {
		return rf(ctx, serverURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MCPOAuthMetadata); ok {
		r0 = rf(ctx, serverURL)
	} else {
		r0 = ret.Get(0).(domain.MCPOAuthMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exchange provides a mock function with given fields: ctx, meta, client, code, verifier, redirectURI
func (_m *MCPOAuthProvider) Exchange(ctx context.Context, meta domain.MCPOAuthMetadata, client domain.MCPOAuthClient, code string, verifier string, redirectURI string) (domain.MCPOAuthToken, error) {
	ret := _m.Called(ctx, meta, client, code, verifier, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 domain.MCPOAuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPOAuthMetadata, domain.MCPOAuthClient, string, string, string) (domain.MCPOAuthToken, error)); ok {
		return rf(ctx, meta, client, code, verifier, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPOAuthMetadata, domain.MCPOAuthClient, string, string, string) domain.MCPOAuthToken); ok {
		r0 = rf(ctx, meta, client, code, verifier, redirectURI)
	} else {
		r0 = ret.Get(0).(domain.MCPOAuthToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MCPOAuthMetadata, domain.MCPOAuthClient, string, string, string) error); ok {
		r1 = rf(ctx, meta, client, code, verifier, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: ctx, meta, client, refreshToken
func (_m *MCPOAuthProvider) Refresh(ctx context.Context, meta domain.MCPOAuthMetadata, client domain.MCPOAuthClient, refreshToken string) (domain.MCPOAuthToken, error) {
	ret := _m.Called(ctx, meta, client, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 domain.MCPOAuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPOAuthMetadata, domain.MCPOAuthClient, string) (domain.MCPOAuthToken, error)); ok {
		return rf(ctx, meta, client, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPOAuthMetadata, domain.MCPOAuthClient, string) domain.MCPOAuthToken); ok {
		r0 = rf(ctx, meta, client, refreshToken)
	} else {
		r0 = ret.Get(0).(domain.MCPOAuthToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MCPOAuthMetadata, domain.MCPOAuthClient, string) error); ok {
		r1 = rf(ctx, meta, client, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, meta, redirectURI
func (_m *MCPOAuthProvider) Register(ctx context.Context, meta domain.MCPOAuthMetadata, redirectURI string) (domain.MCPOAuthClient, error) {
	ret := _m.Called(ctx, meta, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.MCPOAuthClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPOAuthMetadata, string) (domain.MCPOAuthClient, error)); ok {
		return rf(ctx, meta, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPOAuthMetadata, string) domain.MCPOAuthClient); ok {
		r0 = rf(ctx, meta, redirectURI)
	} else {
		r0 = ret.Get(0).(domain.MCPOAuthClient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MCPOAuthMetadata, string) error); ok {
		r1 = rf(ctx, meta, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMCPOAuthProvider creates a new instance of MCPOAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMCPOAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MCPOAuthProvider {
	mock := &MCPOAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
