// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/makifbaysal/tasktrooper/server/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// MCPOAuthStore is an autogenerated mock type for the MCPOAuthStore type
type MCPOAuthStore struct {
	mock.Mock
}

// DeleteMCPOAuth provides a mock function with given fields: ctx, serverID
func (_m *MCPOAuthStore) DeleteMCPOAuth(ctx context.Context, serverID string) error {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMCPOAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMCPOAuth provides a mock function with given fields: ctx, serverID
func (_m *MCPOAuthStore) GetMCPOAuth(ctx context.Context, serverID string) (port.MCPOAuthRecord, bool, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for GetMCPOAuth")
	}

	var r0 port.MCPOAuthRecord
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (port.MCPOAuthRecord, bool, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) port.MCPOAuthRecord); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Get(0).(port.MCPOAuthRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, serverID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SaveMCPOAuth provides a mock function with given fields: ctx, rec
func (_m *MCPOAuthStore) SaveMCPOAuth(ctx context.Context, rec port.MCPOAuthRecord) error {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for SaveMCPOAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, port.MCPOAuthRecord) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMCPOAuthStore creates a new instance of MCPOAuthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMCPOAuthStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MCPOAuthStore {
	mock := &MCPOAuthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
