// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/makifbaysal/tasktrooper/server/internal/domain"
	port "github.com/makifbaysal/tasktrooper/server/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// MCPStore is an autogenerated mock type for the MCPStore type
type MCPStore struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *MCPStore) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, server
func (_m *MCPStore) Create(ctx context.Context, server domain.MCPServer) (domain.MCPServer, error) {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.MCPServer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPServer) (domain.MCPServer, error)); ok {
		return rf(ctx, server)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPServer) domain.MCPServer); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Get(0).(domain.MCPServer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MCPServer) error); ok {
		r1 = rf(ctx, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MCPStore) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSecret provides a mock function with given fields: ctx, serverID, location, key
func (_m *MCPStore) DeleteSecret(ctx context.Context, serverID string, location string, key string) error {
	ret := _m.Called(ctx, serverID, location, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, serverID, location, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSecretsForServer provides a mock function with given fields: ctx, serverID
func (_m *MCPStore) DeleteSecretsForServer(ctx context.Context, serverID string) error {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecretsForServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *MCPStore) Get(ctx context.Context, id string) (domain.MCPServer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.MCPServer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MCPServer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MCPServer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.MCPServer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *MCPStore) List(ctx context.Context) ([]domain.MCPServer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.MCPServer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.MCPServer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.MCPServer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MCPServer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSecrets provides a mock function with given fields: ctx, serverID
func (_m *MCPStore) ListSecrets(ctx context.Context, serverID string) ([]port.MCPSecretRecord, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []port.MCPSecretRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]port.MCPSecretRecord, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []port.MCPSecretRecord); ok {
		r0 = rf(ctx, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.MCPSecretRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSecret provides a mock function with given fields: ctx, serverID, location, key, encrypted
func (_m *MCPStore) SetSecret(ctx context.Context, serverID string, location string, key string, encrypted []byte) error {
	ret := _m.Called(ctx, serverID, location, key, encrypted)

	if len(ret) == 0 {
		panic("no return value specified for SetSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) error); ok {
		r0 = rf(ctx, serverID, location, key, encrypted)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, server
func (_m *MCPStore) Update(ctx context.Context, server domain.MCPServer) (domain.MCPServer, error) {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.MCPServer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPServer) (domain.MCPServer, error)); ok {
		return rf(ctx, server)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MCPServer) domain.MCPServer); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Get(0).(domain.MCPServer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MCPServer) error); ok {
		r1 = rf(ctx, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMCPStore creates a new instance of MCPStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMCPStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MCPStore {
	mock := &MCPStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
