// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/makifbaysal/tasktrooper/server/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// RemoteToolConnector is an autogenerated mock type for the RemoteToolConnector type
type RemoteToolConnector struct {
	mock.Mock
}

// Connect provides a mock function with given fields: ctx, endpoint
func (_m *RemoteToolConnector) Connect(ctx context.Context, endpoint port.RemoteToolEndpoint) ([]port.ToolExecutor, func(), error) {
	ret := _m.Called(ctx, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 []port.ToolExecutor
	var r1 func()
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, port.RemoteToolEndpoint) ([]port.ToolExecutor, func(), error)); ok {
		return rf(ctx, endpoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.RemoteToolEndpoint) []port.ToolExecutor); ok {
		r0 = rf(ctx, endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.ToolExecutor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.RemoteToolEndpoint) func()); ok {
		r1 = rf(ctx, endpoint)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, port.RemoteToolEndpoint) error); ok {
		r2 = rf(ctx, endpoint)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewRemoteToolConnector creates a new instance of RemoteToolConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteToolConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteToolConnector {
	mock := &RemoteToolConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
