// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/makifbaysal/tasktrooper/server/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ToolExecutor is an autogenerated mock type for the ToolExecutor type
type ToolExecutor struct {
	mock.Mock
}

// Definition provides a mock function with no fields
func (_m *ToolExecutor) Definition() domain.ToolDefinition {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Definition")
	}

	var r0 domain.ToolDefinition
	if rf, ok := ret.Get(0).(func() domain.ToolDefinition); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.ToolDefinition)
	}

	return r0
}

// Execute provides a mock function with given fields: ctx, arguments
func (_m *ToolExecutor) Execute(ctx context.Context, arguments string) domain.ToolResult {
	ret := _m.Called(ctx, arguments)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.ToolResult
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ToolResult); ok {
		r0 = rf(ctx, arguments)
	} else {
		r0 = ret.Get(0).(domain.ToolResult)
	}

	return r0
}

// Name provides a mock function with no fields
func (_m *ToolExecutor) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewToolExecutor creates a new instance of ToolExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolExecutor {
	mock := &ToolExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
