package pipeline

import (
	"path"
	"strings"
	"unicode/utf8"
)

func expand(body string, pairs ...string) string {
	return strings.NewReplacer(pairs...).Replace(body)
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func displayText(s string) string {
	clean := strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, s)

	if utf8.RuneCountInString(clean) > 120 {
		clean = string([]rune(clean)[:120])
	}
	return clean
}

const preamble = `#!/usr/bin/env bash
# mobile-release.sh — @APPNAME@ (@PLATFORM@) → @STORE@
#
# GENERATED by agent-server (application/storeops/pipeline). Edit the
# generator; this file is rewritten whenever the store binding changes.
#
# THIS FILE IS THE WHOLE PROCEDURE. The workflow that calls it —
#   @WORKFLOWPATH@
# checks out, installs a toolchain and runs this, and does nothing else on
# purpose. A release procedure kept in two places drifts, and the copy that
# drifts is always the one nobody watches; a step that is not here does not
# exist.
#
#   bash @SCRIPTPATH@ stage     @STAGEDOC@
#   bash @SCRIPTPATH@ prod      @PRODDOC@
#
# prod DOES NOT REBUILD. There is one binary per release and it is the one
# testers used; a fresh build at submission time ships something nobody ran.
#
# Secrets are pushed by the system when the store target is saved — never
# created by hand — and arrive as environment variables:
#
@SECRETDOC@#
# BASH, NOT ZSH. Not a preference, a lost day: under zsh ` + "`\"$app:latest\"`" + ` is a
# MODIFIER (` + "`:l`" + ` lowercases) and silently produced a tag ending in "atest", and
# a failing ` + "`. ./file`" + ` does not stop a zsh script under ` + "`set -e`" + `. The guard
# below is exactly that bug.
set -euo pipefail

if [ -z "${BASH_VERSION:-}" ]; then
  echo "error: run this with bash, not zsh: bash @SCRIPTPATH@ <stage|prod>" >&2
  exit 1
fi

CHANNEL="${1:-}"
case "$CHANNEL" in
  stage|prod) ;;
  *) echo "usage: bash @SCRIPTPATH@ <stage|prod>" >&2; exit 2 ;;
esac

# Everything written below is a private key, a signing identity or a binary
# about to be signed. A umask rather than a chmod per write, which is one
# forgotten line away from a world-readable .p8.
umask 077

die() { echo "error: $*" >&2; exit 1; }
step() { printf '\n==> %s\n' "$*"; }
note() { printf '    %s\n' "$*"; }

# The APP project root, not the repository root: this script sits in
# <project>/scripts, and xcodebuild and gradlew both resolve from <project>.
#
# TT_PROJECT_ROOT exists because TaskTrooper's local engine does NOT run this
# file from the checkout. It sources the procedure it generated from a private
# 0700 run directory — the checkout is a task branch that may predate this
# file or have been edited since — so there $0 is a path in that directory and
# dirname "$0"/.. is not the project at all. Set and not a directory is refused
# rather than fallen back from: the fallback would build whatever happens to
# sit above the run directory.
if [ -n "${TT_PROJECT_ROOT:-}" ]; then
  [ -d "$TT_PROJECT_ROOT" ] || die "TT_PROJECT_ROOT is $TT_PROJECT_ROOT, which is not a directory"
  cd "$TT_PROJECT_ROOT"
else
  cd "$(dirname "$0")/.."
fi
ROOT="$PWD"

# Where both engines look afterwards. The workflow uploads this directory as
# the run's artifact; nothing else in it knows how to build one.
ARTIFACTS="$ROOT/build/mobile-release"
mkdir -p "$ARTIFACTS"

# WORKDIR holds every DECODED secret this run produces — the distribution
# private key, the upload keystore, the Play service account, the temporary
# keychain — so its LIFETIME is the whole question, and the EXIT trap below is
# not an answer on its own: an EXIT trap does not run for SIGKILL, a panic, or
# a Mac losing power.
#
# TT_RELEASE_WORKDIR is how a local engine hands over a directory it already
# owns: 0700, inside a run directory named tasktrooper-release-<hex>, removed
# when the call ends AND swept at the engine's next start (this repository's
# adapter/local/mobilebuild, and the desktop runner's mobile_release.go,
# releaseDirPrefix). That sweep matches on the prefix, so a mktemp -d name —
# tmp.XXXXXX — is invisible to it, and a killed run used to leave a decoded
# distribution key in the user's temp directory until macOS got round to it,
# readable the whole time by everything else running as this user.
#
# Under Actions nothing sets it, the fallback is used and the machine is
# destroyed with the run. The trap stays either way: second line of defence,
# not the first.
if [ -n "${TT_RELEASE_WORKDIR:-}" ]; then
  WORKDIR="$TT_RELEASE_WORKDIR"
  [ -d "$WORKDIR" ] || die "TT_RELEASE_WORKDIR is $WORKDIR, which is not a directory"
else
  WORKDIR="$(mktemp -d)"
fi

require() {
  if [ -z "${!1:-}" ]; then
    die "$1 is not set. Signing secrets are pushed when the store target is saved; a local run has to export them first."
  fi
}

# require_one_line NAME — for the passwords that leave this script on a LINE
# rather than in argv: a ` + "`security -i`" + ` command, a gradle.properties entry.
# Neither can carry an embedded newline, and a password that had one would
# otherwise be silently truncated into a wrong password and a signing failure
# nobody could read.
require_one_line() {
  require "$1"
  case "${!1}" in
    *$'\n'*) die "$1 contains a newline. It has to travel on a single line — re-issue it without one." ;;
  esac
}

# decode_secret NAME DEST — the only place that knows a secret is base64.
#
# Every secret marked base64 above is base64 AT REST, in the vault and in the
# GitHub secret, and every consumer below wants raw bytes.
decode_secret() {
  local name="$1" dest="$2" value
  require "$name"
  value="${!name}"
  # -d, not -D: GNU coreutils has only -d and macOS accepts both, so -d is the
  # single form that works on the runner AND on a paired Mac.
  if ! printf '%s' "$value" | base64 -d > "$dest" 2>/dev/null; then
    die "$name is not valid base64 — it is stored base64-encoded, so something pushed it raw"
  fi
  if [ ! -s "$dest" ]; then
    die "$name decoded to nothing"
  fi
}

# mask_lines registers a DECODED secret with Actions, line by line, from stdin.
#
# GitHub masks the stored secret string and never a derivative of it. Decoding
# a base64 secret produces plaintext Actions has never seen, so unless every
# line is registered by hand an action that echoes its inputs — or
# ACTIONS_STEP_DEBUG — prints a signing key into the log.
#
# WHY THE MASKING IS IN THE SCRIPT AND NOT IN THE WORKFLOW: the decode that
# produces the thing to mask is a step, and every step lives in this file. A
# workflow that masked the key would have to decode it first — a second copy of
# a step this script already owns, which is the exact split this generator
# exists to prevent. So the workflow command is emitted from here and guarded:
# ::add-mask:: means nothing outside Actions, and printing it on a laptop would
# put the key on the operator's terminal instead of hiding it.
mask_lines() {
  if [ -z "${GITHUB_ACTIONS:-}" ]; then
    cat > /dev/null
    return 0
  fi
  local line
  while IFS= read -r line; do
    if [ -n "$line" ]; then
      echo "::add-mask::$line"
    fi
  done
  # Explicit: a while loop takes the exit status of the last command in its
  # body, so a final empty line would return 1 and set -e would kill the
  # pipeline feeding it.
  return 0
}

# resolve_build_number is stage-only. prod ships a build that already exists
# and must not invent a number for it.
#
# TestFlight refuses a build number it has already seen for a marketing version
# and refuses one below the highest it holds; Play refuses a versionCode that
# is not strictly higher. Actions supplies a monotonic run number, and that is
# the ONE series both engines share — which is why a local run has to be told
# where it is in that series instead of inventing a timestamp, because a
# timestamp blocks every CI run after it. A TaskTrooper test build is told the
# same way on either engine: the number it chose arrives as BUILD_NUMBER, from
# the workflow's build_number input or the local engine's environment.
# NOT ` + "`BUILD_NUMBER=\"\"`" + `. That DISCARDED the value the operator exported, so
# the local path failed with the very instruction it prints below — and it made
# the workflow's own BUILD_NUMBER: ${{ inputs.build_number || github.run_number }}
# dead, because only the GITHUB_RUN_NUMBER fallback was ever reached. This line
# exists solely to give set -u something to read.
BUILD_NUMBER="${BUILD_NUMBER:-}"
resolve_build_number() {
  BUILD_NUMBER="${BUILD_NUMBER:-${GITHUB_RUN_NUMBER:-}}"
  if [ -z "$BUILD_NUMBER" ]; then
    die "BUILD_NUMBER is not set and this is not an Actions run.
Pass the next free number in the SAME series CI uses:
  BUILD_NUMBER=<n> bash @SCRIPTPATH@ $CHANNEL"
  fi
  # Defined by each platform below: the two stores do not agree on what a
  # build number IS, so one grammar here would refuse a valid one of either.
  check_build_number "$BUILD_NUMBER"
}
`

const iosBody = `
APP_NAME=@APPNAMEQ@
IDENTIFIER=@IDENTIFIERQ@
SCHEME=@SCHEMEQ@
STORE_APP_ID=@STOREAPPIDQ@

# check_build_number is CFBundleVersion's own grammar: one to three
# period-separated non-negative integers. A TaskTrooper test build is
# <sequence>.<task>.<attempt>, dotted on purpose, so the single-integer check
# this replaced refused every one of them. The regex sits in a variable because
# bash 3.2 — /bin/bash on every Mac — and bash 4+ disagree about a quoted one.
check_build_number() {
  local grammar='^[0-9]+(\.[0-9]+){0,2}$'
  [[ "$1" =~ $grammar ]] || die "BUILD_NUMBER must be one to three dot-separated non-negative integers (CFBundleVersion, e.g. 412 or 412.54.2): $1"
}

# tt-release.keychain-db is a COORDINATED CROSS-REPO NAME, like the
# internalauth wire contract: the local engines' startup sweepers match on this
# exact string to clear keychains left behind when a run is SIGKILLed before
# the trap below can fire (this repository's adapter/local/mobilebuild, and the
# desktop runner's mobile_release.go, releaseKeychainName). Renaming it here
# without renaming it there stops that sweep silently, leaving a signing
# identity in the operator's search list.
KEYCHAIN="$WORKDIR/tt-release.keychain-db"

# The .p8 goes under $WORKDIR, NOT under $HOME. altool searches five places for
# AuthKey_<key id>.p8 — ./private_keys, ~/private_keys, ~/.private_keys,
# ~/.appstoreconnect/private_keys and $API_PRIVATE_KEYS_DIR (` + "`xcrun altool --help`" + `)
# — and that env var is the only one of the five not under $HOME. Writing it to
# ~/.appstoreconnect left an App Store Connect private key on the operator's
# Mac after a SUCCESSFUL run, because cleanup only ever removed $WORKDIR, and
# that key alone is TestFlight and ASC API access.
ASC_KEY_DIR="$WORKDIR/private_keys"
ASC_KEY_PATH=""

# PROFILE_PATH is the one decoded file that CANNOT live in $WORKDIR: xcodebuild
# reads provisioning profiles from this directory under $HOME and takes no
# override for it, so it is removed by name instead.
PROFILE_PATH=""

cleanup() {
  # delete-keychain as well as rm: the file lives in $WORKDIR, but ` + "`security`" + `
  # also has it in the user's keychain SEARCH LIST, and a stale entry there
  # makes every later codesign on this Mac walk a keychain that is gone.
  security delete-keychain "$KEYCHAIN" 2> /dev/null || true
  if [ -n "$PROFILE_PATH" ]; then
    # Nothing of the operator's is lost that was not already lost: decode_secret
    # truncated whatever profile for this bundle id was sitting there.
    rm -f "$PROFILE_PATH"
  fi
  if [ -n "$ASC_KEY_PATH" ]; then
    # The other decoded file outside $WORKDIR, and the one that outlived even a
    # SUCCESSFUL run until this line existed: altool insists on finding the key
    # under $HOME under a name it chooses, so it cannot live in the run
    # directory. On CI the machine is destroyed and nobody noticed; on a paired
    # Mac an App Store Connect private key — TestFlight and the whole ASC API on
    # its own — was simply left on disk after the first release.
    rm -f "$ASC_KEY_PATH"
  fi
  rm -rf "$WORKDIR"
}
trap cleanup EXIT

# sec runs ONE security(1) command with its arguments on STDIN instead of argv.
#
# create-keychain -p, import -P and set-key-partition-list -k all take the
# password as an ARGUMENT and none of them has a file or stdin form — the man
# page says so itself, and says "Use of the -p option is insecure". argv is
# world-readable, which is why the runner already sends its prompt on stdin, and
# an archive runs for minutes with ` + "`ps -ax -o args`" + ` showing the password the
# whole time. ` + "`security -i`" + ` reads one command per line from stdin and exits at
# EOF, so nothing is in argv and nothing is on disk either — printf is a builtin
# and the pipe is a pipe.
#
# ONE command per call, never a batch. In interactive mode security CONTINUES
# after a failed command and exits with the status of the LAST one, so a batch
# would hide a refused import behind a later success and set -e would never
# fire. One command means the session's status IS that command's status.
sec() {
  printf '%s\n' "$*" | security -i
}

# secq quotes one argument for that tokenizer. Inside "..." only \ and " are
# special; spaces, $, backtick, ; and # are literal — which is the whole reason
# a password can be passed this way at all.
secq() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

preflight() {
  step "preflight: $APP_NAME ($IDENTIFIER) → $CHANNEL"
  if [ "$(uname -s)" != "Darwin" ]; then
    die "xcodebuild only exists on macOS — this needs a macos runner or a paired Mac"
  fi
  command -v xcodebuild > /dev/null || die "xcodebuild not found (install Xcode, then xcode-select --install)"
  require ASC_KEY_ID
  require ASC_ISSUER_ID
  note "scheme       : $SCHEME"
  note "asc app id   : ${STORE_APP_ID:-(not recorded)}"
}

# asc_key sets ASC_KEY_PATH to the one directory altool and fastlane both
# search, under the name they both expect.
#
# The path comes back in a variable rather than on stdout deliberately: stdout
# here is the job log, which is where the ::add-mask:: lines below have to
# land, and a command substitution would swallow them.
asc_key() {
  mkdir -p "$ASC_KEY_DIR"
  ASC_KEY_PATH="$ASC_KEY_DIR/AuthKey_${ASC_KEY_ID}.p8"
  decode_secret ASC_KEY_P8 "$ASC_KEY_PATH"
  # The name is not ours to choose: altool looks for AuthKey_<key id>.p8 and
  # nothing else. fastlane needs none of this — it is handed key_filepath
  # directly below — so the variable is what both paths actually use.
  export API_PRIVATE_KEYS_DIR="$ASC_KEY_DIR"
  mask_lines < "$ASC_KEY_PATH"
}

release_stage() {
  resolve_build_number
  note "build number : $BUILD_NUMBER"

  step "import the distribution certificate"
  decode_secret IOS_DIST_CERT_P12 "$WORKDIR/dist.p12"
  require_one_line IOS_CERT_PASSWORD
  local keychain_password
  keychain_password="$(openssl rand -hex 16)"
  # Every password below goes through sec/secq, so none of them is in argv.
  # set-keychain-settings and list-keychains take no password and stay direct.
  sec "create-keychain -p $(secq "$keychain_password") $(secq "$KEYCHAIN")"
  security set-keychain-settings -lut 21600 "$KEYCHAIN"
  sec "unlock-keychain -p $(secq "$keychain_password") $(secq "$KEYCHAIN")"
  sec "import $(secq "$WORKDIR/dist.p12") -k $(secq "$KEYCHAIN") -P $(secq "$IOS_CERT_PASSWORD") -T /usr/bin/codesign -T /usr/bin/security -f pkcs12" > /dev/null
  # Without the partition list codesign raises a GUI keychain prompt no runner
  # can answer and the build hangs until the job times out. It is the classic
  # "iOS CI hung for six hours", and it produces no error message at all.
  sec "set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $(secq "$keychain_password") $(secq "$KEYCHAIN")" > /dev/null
  # PREPENDED to the search list, not substituted for it: on a developer's own
  # Mac a replaced list is what breaks their next build.
  local kc
  local existing=()
  while IFS= read -r kc; do
    kc="${kc#*\"}"
    kc="${kc%\"*}"
    if [ -n "$kc" ]; then
      existing+=("$kc")
    fi
  done < <(security list-keychains -d user)
  security list-keychains -d user -s "$KEYCHAIN" ${existing[@]+"${existing[@]}"} > /dev/null

  step "install the provisioning profile"
  local profiles="$HOME/Library/MobileDevice/Provisioning Profiles"
  mkdir -p "$profiles"
  # Recorded BEFORE the decode, so an interrupted write is still removed by the
  # trap. This is the file that outlived a successful run.
  PROFILE_PATH="$profiles/$IDENTIFIER.mobileprovision"
  decode_secret IOS_PROFILE_B64 "$PROFILE_PATH"

  step "archive"
  xcodebuild -scheme "$SCHEME" -configuration Release \
    -archivePath "$ARTIFACTS/app.xcarchive" \
    -destination 'generic/platform=iOS' \
    archive \
    CODE_SIGN_STYLE=Manual \
    PRODUCT_BUNDLE_IDENTIFIER="$IDENTIFIER" \
    CURRENT_PROJECT_VERSION="$BUILD_NUMBER"

  step "export the IPA"
  cat > "$WORKDIR/ExportOptions.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>method</key><string>app-store-connect</string>
</dict></plist>
PLIST
  xcodebuild -exportArchive \
    -archivePath "$ARTIFACTS/app.xcarchive" \
    -exportPath "$ARTIFACTS/ipa" \
    -exportOptionsPlist "$WORKDIR/ExportOptions.plist"

  local ipa
  # -print -quit rather than a pipe into head: under ` + "`set -o pipefail`" + ` head
  # closing early makes find die of SIGPIPE and takes the whole script with it.
  ipa="$(find "$ARTIFACTS/ipa" -maxdepth 1 -name '*.ipa' -print -quit 2> /dev/null || true)"
  if [ -z "$ipa" ]; then
    die "the export produced no .ipa under $ARTIFACTS/ipa"
  fi
  note "ipa: $ipa"

  # The IPA is on disk BEFORE the upload is attempted, so a refused upload
  # still leaves a downloadable signed build. That is the whole first-publish
  # path: App Store Connect has no app record yet and the binary goes up by
  # hand once.
  step "upload to TestFlight"
  asc_key
  if ! xcrun altool --upload-app --type ios --file "$ipa" \
      --apiKey "$ASC_KEY_ID" --apiIssuer "$ASC_ISSUER_ID" 2>&1 | tee "$ARTIFACTS/upload.log"; then
    if grep -qiE 'no app|cannot find|not found|does not exist' "$ARTIFACTS/upload.log"; then
      die "App Store Connect has no app record for $IDENTIFIER yet, so this build cannot be uploaded by API.
Create the app in App Store Connect and re-run this channel. The signed IPA is already here:
  $ipa"
    fi
    die "altool refused the upload; the whole answer is in $ARTIFACTS/upload.log"
  fi
  note "build $BUILD_NUMBER is on its way to TestFlight"
}

release_prod() {
  # NO archive, NO export, NO upload. This channel submits the build testers
  # already have; building here would put a binary nobody ran in front of users.
  step "submit the current TestFlight build for App Store review"
  command -v fastlane > /dev/null || die "fastlane not found (gem install fastlane --no-document)"
  asc_key

  local version
  version="$(xcodebuild -scheme "$SCHEME" -showBuildSettings | awk '/MARKETING_VERSION/{print $3; exit}')"
  if [ -z "$version" ]; then
    die "could not read MARKETING_VERSION out of the $SCHEME build settings"
  fi
  note "marketing version: $version"

  cat > "$WORKDIR/api_key.json" <<JSON
{"key_id": "$ASC_KEY_ID", "issuer_id": "$ASC_ISSUER_ID", "key_filepath": "$ASC_KEY_PATH"}
JSON

  fastlane run app_store_connect_api_key \
    key_filepath:"$ASC_KEY_PATH" key_id:"$ASC_KEY_ID" issuer_id:"$ASC_ISSUER_ID"
  # --skip_binary_upload is the load-bearing flag: without it deliver hunts for
  # a binary to push and this channel has none, by design.
  fastlane deliver \
    --api_key_path "$WORKDIR/api_key.json" \
    --app_identifier "$IDENTIFIER" \
    --app_version "$version" \
    --skip_binary_upload true --skip_screenshots --skip_metadata --force \
    --submit_for_review --automatic_release false --phased_release
}
`

const androidBody = `
APP_NAME=@APPNAMEQ@
IDENTIFIER=@IDENTIFIERQ@
MODULE=@MODULEQ@

# Play's staged rollout for the production track. Not a field of the store
# binding: it is an operational choice per release, so it is read here with the
# same default the old template carried rather than frozen at generation time.
ROLLOUT="${PLAY_ROLLOUT_FRACTION:-0.2}"

# A brand-new Play app CANNOT receive its first bundle through the API — the
# first one has to be uploaded by hand in Play Console. Set this false for that
# one run: the script still builds and signs the AAB, says exactly where it is
# and stops. Every later build goes up by API with the default.
UPLOAD="${MOBILE_RELEASE_UPLOAD:-true}"

PLAY_KEY_PATH=""
AAB=""

# check_build_number is versionCode's grammar: ONE positive integer — Play has
# no dotted form — and no larger than 2100000000, Play's ceiling, which it
# enforces at upload, after the whole build. The length test comes first
# because ` + "`[ -gt ]`" + ` on a number past 64 bits is an error, and an error in an if
# condition is just false: the bound would wave it through.
check_build_number() {
  case "$1" in
    ''|0*|*[!0-9]*) die "BUILD_NUMBER must be a positive integer (versionCode) with no leading zero: $1" ;;
  esac
  if [ "${#1}" -gt 10 ] || [ "$1" -gt 2100000000 ]; then
    die "BUILD_NUMBER must be no larger than 2100000000, Play's versionCode ceiling: $1"
  fi
}

# A Gradle home this RUN owns, so gradle.properties below is a file only this
# run can see and cleanup takes with it.
GRADLE_RUN_HOME="$WORKDIR/gradle-home"

cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

preflight() {
  step "preflight: $APP_NAME ($IDENTIFIER) → $CHANNEL"
  command -v java > /dev/null || die "java not found (a Play build needs a JDK; CI uses temurin 17)"
  note "module       : $MODULE"
  note "rollout      : $ROLLOUT"
}

# play_key sets PLAY_KEY_PATH. Like asc_key on the other platform it answers in
# a variable, because the ::add-mask:: lines belong on the job log and a
# command substitution would swallow them.
# need_fastlane is checked where fastlane is USED, not in preflight: the
# first-publish path below builds a bundle and uploads nothing, and refusing
# that run for a missing gem would block the one channel onboarding needs.
need_fastlane() {
  command -v fastlane > /dev/null || die "fastlane not found (gem install fastlane --no-document) — supply is how this script talks to Play"
}

play_key() {
  PLAY_KEY_PATH="$WORKDIR/play_sa.json"
  decode_secret PLAY_SA_JSON "$PLAY_KEY_PATH"
  mask_lines < "$PLAY_KEY_PATH"
}

# prop_escape makes one value safe as a Java .properties value.
#
# A backslash starts an escape there and a trailing one continues the line, so
# every backslash is doubled; leading whitespace is stripped by the parser, so
# the first character is escaped if it is any. Nothing else is special once the
# key= prefix is written — :, = and # inside a value are literal. Java reads the
# stream as ISO-8859-1, so a non-ASCII password arrives mangled whatever is done
# here; keep these ASCII.
prop_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/^[[:space:]]/\\&/'
}

# signing_properties writes the injected signing values into a gradle.properties
# inside GRADLE_RUN_HOME instead of passing them as -P arguments.
#
# -P puts the keystore password, the key password and the alias in the argv of a
# JVM that lives for the whole build, where anything running as this user reads
# them out of ` + "`ps -ax -o args`" + `. Gradle reads gradle.properties from the Gradle
# user home (` + "`gradle --help`" + `: -g, --gradle-user-home; the wrapper's own
# GradleWrapperMain honours --gradle-user-home too), and there is no flag that
# points at a properties file alone — which is why the home moves rather than
# the file. umask 077 at the top is what makes it 0600.
#
# store.file must be ABSOLUTE. Gradle resolves an injected signing path against
# the MODULE directory rather than the invocation directory, so a relative one
# silently becomes $MODULE/upload.keystore and the build fails naming a path
# nobody wrote.
signing_properties() {
  local keystore="$1" store_password key_alias key_password
  require_one_line ANDROID_KEYSTORE_PASSWORD
  require_one_line ANDROID_KEY_ALIAS
  require_one_line ANDROID_KEY_PASSWORD
  # Expanded here rather than inside the command substitutions below: a failed
  # expansion there would kill only the subshell and leave an empty password in
  # the file.
  store_password="$ANDROID_KEYSTORE_PASSWORD"
  key_alias="$ANDROID_KEY_ALIAS"
  key_password="$ANDROID_KEY_PASSWORD"

  mkdir -p "$GRADLE_RUN_HOME"
  # A private Gradle home is otherwise a COLD one: the wrapper re-downloads the
  # distribution and every dependency on each release, which on a paired Mac is
  # a quarter of an hour of network. These are links to the shared caches, so
  # only the properties file is actually private.
  local shared="${GRADLE_USER_HOME:-$HOME/.gradle}" dir
  for dir in caches wrapper jdks native; do
    if [ -d "$shared/$dir" ] && [ ! -e "$GRADLE_RUN_HOME/$dir" ]; then
      ln -s "$shared/$dir" "$GRADLE_RUN_HOME/$dir"
    fi
  done

  {
    printf 'android.injected.signing.store.file=%s\n' "$(prop_escape "$keystore")"
    printf 'android.injected.signing.store.password=%s\n' "$(prop_escape "$store_password")"
    printf 'android.injected.signing.key.alias=%s\n' "$(prop_escape "$key_alias")"
    printf 'android.injected.signing.key.password=%s\n' "$(prop_escape "$key_password")"
  } > "$GRADLE_RUN_HOME/gradle.properties"
}

release_stage() {
  resolve_build_number
  note "version code : $BUILD_NUMBER"

  step "restore the upload keystore"
  local keystore="$WORKDIR/upload.keystore"
  decode_secret ANDROID_UPLOAD_KEYSTORE_B64 "$keystore"

  step "build the signed bundle"
  if [ ! -x "$ROOT/gradlew" ]; then
    die "no executable ./gradlew in $ROOT"
  fi
  signing_properties "$keystore"
  # versionCode stays on the command line: it is a build number, not a secret,
  # and keeping it here is what makes the argv readable when a build is being
  # diagnosed. Every signing value went into gradle.properties above.
  #
  # Twice, because -PversionCode only reaches a build.gradle that READS that
  # property, and most hardcode versionCode instead — so the bundle would carry
  # the project's own number, one Play already holds and refuses.
  # android.injected.version.code is the Android Gradle plugin's own override
  # (what Android Studio uses), applied to the merged manifest whatever the
  # build script says.
  "$ROOT/gradlew" ":$MODULE:bundleRelease" \
    -g "$GRADLE_RUN_HOME" \
    -PversionCode="$BUILD_NUMBER" \
    -Pandroid.injected.version.code="$BUILD_NUMBER"

  local built
  # -print -quit rather than a pipe into head: under ` + "`set -o pipefail`" + ` head
  # closing early makes find die of SIGPIPE and takes the whole script with it.
  built="$(find "$ROOT/$MODULE/build/outputs/bundle/release" -maxdepth 1 -name '*.aab' -print -quit 2> /dev/null || true)"
  if [ -z "$built" ]; then
    die "the build produced no .aab under $ROOT/$MODULE/build/outputs/bundle/release"
  fi
  # Copied into $ARTIFACTS before anything is uploaded, so a refused upload
  # still leaves a signed bundle for the by-hand path below.
  AAB="$ARTIFACTS/$(basename "$built")"
  cp "$built" "$AAB"
  note "aab: $AAB"

  if [ "$UPLOAD" != "true" ]; then
    step "upload skipped on purpose"
    cat <<MSG
MOBILE_RELEASE_UPLOAD=$UPLOAD, so nothing was sent to Play.

This is the first-publish path: Play will not accept a brand-new app's first
bundle over the API. Upload this file once by hand — Play Console › Testing ›
Internal testing › Create new release — and every later run uploads itself:

  $AAB
MSG
    return 0
  fi

  step "upload to the internal track"
  need_fastlane
  play_key
  if ! fastlane run supply \
      package_name:"$IDENTIFIER" json_key:"$PLAY_KEY_PATH" aab:"$AAB" track:internal \
      skip_upload_metadata:true skip_upload_changelogs:true \
      skip_upload_images:true skip_upload_screenshots:true 2>&1 | tee "$ARTIFACTS/upload.log"; then
    if grep -qiE 'package not found|cannot find package|only.*play console' "$ARTIFACTS/upload.log"; then
      die "Play has no release for $IDENTIFIER yet, so this FIRST bundle cannot go up over the API.
Upload it by hand in Play Console once, then re-run. The signed bundle is here:
  $AAB"
    fi
    die "supply refused the upload; the whole answer is in $ARTIFACTS/upload.log"
  fi
  note "versionCode $BUILD_NUMBER is on the internal track"
}

release_prod() {
  # NO gradlew, NO bundle. This channel PROMOTES what the internal track
  # already holds; rebuilding would put a different binary in front of users
  # than the one that was tested.
  step "promote internal → production, $ROLLOUT staged rollout"
  need_fastlane
  play_key
  fastlane run supply \
    package_name:"$IDENTIFIER" json_key:"$PLAY_KEY_PATH" \
    track:internal track_promote_to:production rollout:"$ROLLOUT" \
    skip_upload_apk:true skip_upload_aab:true skip_upload_metadata:true \
    skip_upload_changelogs:true skip_upload_images:true skip_upload_screenshots:true
}
`

const dispatch = `
preflight
case "$CHANNEL" in
  stage) release_stage ;;
  prod) release_prod ;;
esac
step "done"
`

const iosSecretDoc = `#   IOS_DIST_CERT_P12   base64  PKCS#12 distribution certificate and key
#   IOS_CERT_PASSWORD   plain   what opens that PKCS#12
#   IOS_PROFILE_B64     base64  provisioning profile for the bundle id
#   ASC_KEY_ID          plain   App Store Connect API key id
#   ASC_ISSUER_ID       plain   App Store Connect issuer id
#   ASC_KEY_P8          base64  the .p8 private key
#
# The three marked base64 are base64 AT REST — in the vault and in the GitHub
# secret — and every consumer below wants raw bytes, so each is decoded here.
`

const androidSecretDoc = `#   ANDROID_UPLOAD_KEYSTORE_B64  base64  the upload keystore
#   ANDROID_KEYSTORE_PASSWORD    plain   what opens that keystore
#   ANDROID_KEY_ALIAS            plain   key entry inside it
#   ANDROID_KEY_PASSWORD         plain   what opens that key entry
#   PLAY_SA_JSON                 base64  Play service-account JSON
#
# The two marked base64 are base64 AT REST — in the vault and in the GitHub
# secret — and every consumer below wants raw bytes, so each is decoded here.
`

func iosScript(s Spec) string {
	return expand(preamble+iosBody+dispatch,
		"@APPNAME@", displayText(s.AppName),
		"@APPNAMEQ@", shellQuote(displayText(s.AppName)),
		"@PLATFORM@", "native iOS",
		"@STORE@", "App Store Connect",
		"@STAGEDOC@", "archive, sign, upload to TestFlight",
		"@PRODDOC@", "submit the tested TestFlight build for review",
		"@SECRETDOC@", iosSecretDoc,
		"@SCRIPTPATH@", s.runFromRoot(),
		"@WORKFLOWPATH@", s.workflowPath(),
		"@IDENTIFIERQ@", shellQuote(s.Identifier),
		"@SCHEMEQ@", shellQuote(s.Scheme),
		"@STOREAPPIDQ@", shellQuote(s.StoreAppID),
	)
}

func androidScript(s Spec) string {
	return expand(preamble+androidBody+dispatch,
		"@APPNAME@", displayText(s.AppName),
		"@APPNAMEQ@", shellQuote(displayText(s.AppName)),
		"@PLATFORM@", "native Android",
		"@STORE@", "Google Play",
		"@STAGEDOC@", "build a signed AAB, upload to the Internal testing track",
		"@PRODDOC@", "promote internal → production with a staged rollout",
		"@SECRETDOC@", androidSecretDoc,
		"@SCRIPTPATH@", s.runFromRoot(),
		"@WORKFLOWPATH@", s.workflowPath(),
		"@IDENTIFIERQ@", shellQuote(s.Identifier),
		"@MODULEQ@", shellQuote(s.Module),
	)
}

func (s Spec) artifactsGlob() string {
	return path.Join(s.SubProjectPath, "build", "mobile-release") + "/**"
}
