package pipeline

const iosWorkflowBody = `# GENERATED by agent-server (application/storeops/pipeline). Edit the
# generator, not this file.
#
# A WRAPPER. Every step of the release lives in
#   @SCRIPTPATH@
# so this run and a local run do the same thing. A step added here would exist
# only under Actions, and the copy nobody watches is always the one that
# drifts.
name: mobile-release
@RUNNAME@
on:
  workflow_dispatch:
    inputs:
      channel:
        description: "stage = build and upload to TestFlight; prod = submit the tested build for App Store review (no rebuild)"
        type: choice
        options: [stage, prod]
        default: stage
      build_number:
        description: "Build number for this run (CFBundleVersion: 1 to 3 dot-separated integers). Empty = this run's number."
        type: string
        default: ""
@TESTINPUTS@
# Keyed on the APP, not the repository: two apps in one monorepo release
# independently, and two runs against the same app must never race for one
# build number or one App Store Connect submission. Not cancelled in flight —
# a half-uploaded binary is worse than a queued run.
@CONCURRENCY@
jobs:
  release:
    # Apple's toolchain exists nowhere else.
    runs-on: macos-14
    steps:
@CHECKOUT@
      # macos images ship fastlane, but prod is the one channel that cannot
      # proceed without it, so it is made certain there rather than assumed.
      - if: inputs.channel == 'prod'
        run: gem install fastlane --no-document

      - name: Release
        # Everything reaches the script through the ENVIRONMENT. ${{ }} inside
        # a run: block is textual substitution into the shell line, and the
        # only reason it would be safe here is that channel is a choice input —
        # which is not a property to depend on the next time an input is added.
        env:
          CHANNEL: ${{ inputs.channel }}
          BUILD_NUMBER: ${{ inputs.build_number || github.run_number }}
          IOS_DIST_CERT_P12: ${{ secrets.IOS_DIST_CERT_P12 }}
          IOS_CERT_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
          IOS_PROFILE_B64: ${{ secrets.IOS_PROFILE_B64 }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
        # Invoked through bash explicitly: the file is generated 0755 with a
        # bash shebang, and this is the second guard on the one mistake that
        # cost a day (see the script's own header).
        run: bash @SCRIPTPATH@ "$CHANNEL"

      # The one thing the script cannot do for itself: make what it produced
      # downloadable. always(), because the script writes the signed build
      # BEFORE attempting an upload — which is the whole first-publish path,
      # where the store has no app record yet and the binary goes up by hand.
@ARTIFACT@`

const androidWorkflowBody = `# GENERATED by agent-server (application/storeops/pipeline). Edit the
# generator, not this file.
#
# A WRAPPER. Every step of the release lives in
#   @SCRIPTPATH@
# so this run and a local run do the same thing. A step added here would exist
# only under Actions, and the copy nobody watches is always the one that
# drifts.
name: mobile-release
@RUNNAME@
on:
  workflow_dispatch:
    inputs:
      channel:
        description: "stage = build a signed AAB and upload to Internal testing; prod = promote internal to production (no rebuild)"
        type: choice
        options: [stage, prod]
        default: stage
      upload:
        description: "Upload to the internal track. Set false for a brand-new app: Play only accepts its FIRST bundle by hand, and the run's artifact is what you upload."
        type: boolean
        default: true
      rollout:
        description: "Production staged rollout fraction (prod only)"
        type: string
        default: "0.2"
      build_number:
        description: "Build number for this run (versionCode: one positive integer). Empty = this run's number."
        type: string
        default: ""
@TESTINPUTS@
# Keyed on the APP, not the repository: two apps in one monorepo release
# independently, and two runs against the same app must never race for one
# versionCode or one Play track. Not cancelled in flight — a half-uploaded
# bundle is worse than a queued run.
@CONCURRENCY@
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
@CHECKOUT@
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      # fastlane supply is how the script talks to Play on BOTH channels.
      - run: gem install fastlane --no-document

      - name: Release
        # Everything reaches the script through the ENVIRONMENT. ${{ }} inside
        # a run: block is textual substitution into the shell line, and the
        # only reason it would be safe here is that channel is a choice input —
        # which is not a property to depend on the next time an input is added.
        env:
          CHANNEL: ${{ inputs.channel }}
          BUILD_NUMBER: ${{ inputs.build_number || github.run_number }}
          MOBILE_RELEASE_UPLOAD: ${{ inputs.upload }}
          PLAY_ROLLOUT_FRACTION: ${{ inputs.rollout }}
          ANDROID_UPLOAD_KEYSTORE_B64: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_B64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          PLAY_SA_JSON: ${{ secrets.PLAY_SA_JSON }}
        # Invoked through bash explicitly: the file is generated 0755 with a
        # bash shebang, and this is the second guard on the one mistake that
        # cost a day (see the script's own header).
        run: bash @SCRIPTPATH@ "$CHANNEL"

      # The one thing the script cannot do for itself: make what it produced
      # downloadable. always(), because the script writes the signed bundle
      # BEFORE attempting an upload — which is the whole first-publish path,
      # where Play refuses the first AAB over the API and it goes up by hand.
@ARTIFACT@`

// The parts below are the same on both platforms and are spliced into each
// body, so a test build behaves identically whichever store it is for.

const runNamePart = `# How TaskTrooper finds the run it dispatched: a workflow_dispatch answers with
# no run id, so a test build puts its own id in the run's title and looks the
# run up by that. A dispatch without one — a person pressing Run workflow —
# keeps the plain name.
run-name: ${{ inputs.build_id != '' && format('tt-test-build {0}', inputs.build_id) || 'mobile-release' }}
`

const testInputsPart = `      ref:
        description: "Commit, branch or tag to build. Empty = the ref this run was dispatched on."
        type: string
        default: ""
      build_id:
        description: "Set by TaskTrooper on a test build so it can find this run and its artifact. Leave empty."
        type: string
        default: ""
`

const concurrencyPart = `#
# A TaskTrooper test build adds its own id. Its number was chosen for it and
# cannot collide, and sharing the app's group would CANCEL it: Actions keeps one
# pending run per group and cancels that one when another is queued, so a third
# task's build would silently replace the second's.
concurrency:
  group: mobile-${{ inputs.channel }}-@IDENTIFIER@${{ inputs.build_id != '' && format('-{0}', inputs.build_id) || '' }}
  cancel-in-progress: false
`

const checkoutPart = `      # The ref to BUILD. Empty is the dispatched ref, which is what a person
      # pressing the button means; a test build names its task's commit.
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      # The PROCEDURE is the dispatched commit's, whichever ref is built. A task
      # branch cut before the pipeline was generated has no release script, or
      # an older one; the current script is committed to the branch this run
      # was dispatched on, so that commit supplies the procedure and the built
      # ref only the code. GITHUB_SHA stays the dispatched commit whatever the
      # checkout above moved to, and it is read from the environment rather
      # than substituted into the line.
      - if: inputs.ref != ''
        run: git fetch --no-tags --depth=1 origin "$GITHUB_SHA" && git checkout "$GITHUB_SHA" -- @SCRIPTPATH@
`

const artifactPart = `      - if: always()
        uses: actions/upload-artifact@v4
        with:
          # Per test build as well as per app, so the artifact TaskTrooper
          # downloads is the one its own dispatch produced.
          name: mobile-release-@IDENTIFIER@${{ inputs.build_id != '' && format('-{0}', inputs.build_id) || '' }}
          path: @ARTIFACTSGLOB@
          if-no-files-found: ignore
`

func workflowParts(body string, s Spec) string {
	body = expand(body,
		"@RUNNAME@", runNamePart,
		"@TESTINPUTS@", testInputsPart,
		"@CONCURRENCY@", concurrencyPart,
		"@CHECKOUT@", checkoutPart,
		"@ARTIFACT@", artifactPart,
	)
	return expand(body,
		"@SCRIPTPATH@", s.runFromRoot(),
		"@IDENTIFIER@", s.Identifier,
		"@ARTIFACTSGLOB@", s.artifactsGlob(),
	)
}

func iosWorkflow(s Spec) string {
	return workflowParts(iosWorkflowBody, s)
}

func androidWorkflow(s Spec) string {
	return workflowParts(androidWorkflowBody, s)
}
