import type { MCPEnvSchemaField, MCPServerCreateInput } from "@/api";
import { exampleFolderPath } from "@/lib/platform";

export interface MCPTemplate extends MCPServerCreateInput {
  label: string;
  description: string;
  env_schema?: MCPEnvSchemaField[];
  secret_fields?: string[];
}

export const MCP_TEMPLATES: MCPTemplate[] = [
  {
    id: "filesystem",
    label: "Filesystem",
    description: "Filesystem access",
    enabled: false,
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", ""],
    env_schema: [{ key: "path", label: "Accessible directory", placeholder: exampleFolderPath() }],
  },
  {
    // Upstream never shipped this one to npm; it is a Python package and uvx is
    // the only first-party way to run it.
    id: "git",
    label: "Git",
    description: "Git repository operations",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["mcp-server-git", "--repository", "."],
  },
  {
    // @modelcontextprotocol/server-github was deprecated; GitHub's own server is
    // remote, so there is nothing to install.
    id: "github",
    label: "GitHub",
    description: "GitHub API integration",
    enabled: false,
    transport: "http",
    url: "https://api.githubcopilot.com/mcp/",
    headers: { Authorization: "Bearer ${GITHUB_TOKEN}" },
    secret_fields: ["header:Authorization"],
    env_schema: [
      { key: "Authorization", label: "GitHub Token", secret: true, placeholder: "Bearer ghp_..." },
    ],
  },
  {
    id: "gitlab",
    label: "GitLab",
    description: "GitLab projects, merge requests, issues and pipelines",
    enabled: false,
    transport: "stdio",
    command: "npx",
    args: ["-y", "@zereight/mcp-gitlab"],
    env: {
      GITLAB_PERSONAL_ACCESS_TOKEN: "${GITLAB_TOKEN}",
      GITLAB_API_URL: "https://gitlab.com/api/v4",
    },
    secret_fields: ["GITLAB_PERSONAL_ACCESS_TOKEN"],
    env_schema: [
      { key: "GITLAB_PERSONAL_ACCESS_TOKEN", label: "GitLab Token", secret: true },
      { key: "GITLAB_API_URL", label: "GitLab API URL", placeholder: "https://gitlab.com/api/v4" },
    ],
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    description: "PostgreSQL database",
    enabled: false,
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-postgres", "${POSTGRES_URL}"],
  },
  {
    id: "slack",
    label: "Slack",
    description: "Slack messaging",
    enabled: false,
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-slack"],
    env: { SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}", SLACK_TEAM_ID: "${SLACK_TEAM_ID}" },
    secret_fields: ["SLACK_BOT_TOKEN"],
    env_schema: [
      { key: "SLACK_BOT_TOKEN", label: "Slack Bot Token", secret: true },
      { key: "SLACK_TEAM_ID", label: "Slack Team ID" },
    ],
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    description: "Model search",
    enabled: false,
    transport: "http",
    url: "https://huggingface.co/mcp",
    headers: { Authorization: "Bearer ${HF_TOKEN}" },
    allowed_tools: ["model_search"],
    secret_fields: ["header:Authorization"],
    env_schema: [{ key: "Authorization", label: "Bearer Token", secret: true }],
  },
  {
    id: "browser",
    label: "Browser",
    description: "Browser automation",
    enabled: true,
    transport: "stdio",
    command: "npx",
    args: ["-y", "@browsermcp/mcp@latest"],
  },
  {
    // Talks to the MCP for Unity package inside the project over a local bridge,
    // so the editor has to be open.
    id: "unity",
    label: "Unity (MCP for Unity)",
    description: "Unity Editor: scenes, assets, scripts, tests",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["--from", "mcpforunityserver==10.3.0", "mcp-for-unity", "--transport", "stdio"],
    env: { DISABLE_TELEMETRY: "true", UNITY_MCP_DEFAULT_INSTANCE: "" },
    env_schema: [{ key: "UNITY_MCP_DEFAULT_INSTANCE", label: "Editor instance (when several are open)" }],
  },
  {
    // The pin must match the project's addons/godot_ai version.
    id: "godot",
    label: "Godot (Godot AI)",
    description: "Godot editor: scenes, nodes, scripts, tests",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["--from", "godot-ai==4.3.0", "godot-ai", "attach", "--disable-telemetry"],
  },
  {
    id: "unreal",
    label: "Unreal Engine (Unreal MCP)",
    description: "Unreal Editor's built-in MCP server (UE 5.8+)",
    enabled: false,
    transport: "http",
    url: "http://127.0.0.1:8000/mcp",
  },
  {
    id: "blender",
    label: "Blender (MCP for Blender)",
    description: "Blender: models, materials, renders, assets",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["mcp-for-blender"],
    env: { DISABLE_TELEMETRY: "true", BLENDER_MCP_SAFE_MODE: "1" },
  },
  {
    id: "jupyter",
    label: "Jupyter",
    description: "Read, edit and run cells in a running JupyterLab",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["jupyter-mcp-server==2.2.3"],
    env: { JUPYTER_URL: "http://localhost:8888", JUPYTER_TOKEN: "${JUPYTER_TOKEN}", ALLOW_IMG_OUTPUT: "true" },
    secret_fields: ["JUPYTER_TOKEN"],
    env_schema: [
      { key: "JUPYTER_URL", label: "JupyterLab URL", placeholder: "http://localhost:8888" },
      { key: "JUPYTER_TOKEN", label: "Jupyter token", secret: true },
    ],
  },
  {
    id: "duckdb",
    label: "DuckDB / MotherDuck",
    description: "SQL over DuckDB files, Parquet and CSV",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["mcp-server-motherduck", "--db-path", ":memory:", "--read-write"],
  },
  {
    id: "dbt",
    label: "dbt",
    description: "dbt lineage, compile, test and run (dbt Core)",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["dbt-mcp"],
    env: { DBT_PROJECT_DIR: "", DBT_PATH: "" },
    env_schema: [
      { key: "DBT_PROJECT_DIR", label: "dbt project folder", placeholder: "/path/to/project" },
      { key: "DBT_PATH", label: "dbt executable", placeholder: "/usr/local/bin/dbt" },
    ],
  },
  {
    id: "mlflow",
    label: "MLflow",
    description: "MLflow experiments, runs, models and traces",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["--from", "mlflow[mcp]>=3.5.1", "mlflow", "mcp", "run"],
    env: { MLFLOW_TRACKING_URI: "http://localhost:5000", MLFLOW_MCP_TOOLS: "ml" },
    env_schema: [{ key: "MLFLOW_TRACKING_URI", label: "Tracking URI", placeholder: "http://localhost:5000" }],
  },
  {
    id: "semgrep",
    label: "Semgrep",
    description: "Local static analysis with Semgrep rules",
    enabled: false,
    transport: "stdio",
    command: "uvx",
    args: ["--from", "semgrep==1.180.0", "semgrep", "mcp"],
    env: { SEMGREP_SEND_METRICS: "off" },
  },
  {
    // No npx/uvx form: install the osv-scanner binary (brew or go install).
    id: "osv-scanner",
    label: "OSV-Scanner",
    description: "Known-vulnerable dependencies in lockfiles",
    enabled: false,
    transport: "stdio",
    command: "osv-scanner",
    args: ["experimental-mcp"],
  },
  {
    id: "github-security",
    label: "GitHub security (read-only)",
    description: "Code scanning, secret scanning and Dependabot alerts",
    enabled: false,
    transport: "http",
    url: "https://api.githubcopilot.com/mcp/",
    headers: {
      Authorization: "Bearer ${GITHUB_TOKEN}",
      "X-MCP-Toolsets": "repos,pull_requests,code_security,secret_protection,dependabot,security_advisories",
      "X-MCP-Readonly": "true",
      "X-MCP-Lockdown": "true",
    },
    secret_fields: ["header:Authorization"],
    env_schema: [
      { key: "Authorization", label: "GitHub token (read-only)", secret: true, placeholder: "Bearer github_pat_..." },
    ],
  },
  {
    // Snyk Code uploads the scanned source to Snyk's cloud.
    id: "snyk",
    label: "Snyk",
    description: "Snyk Code, Open Source, IaC and container scans",
    enabled: false,
    transport: "stdio",
    command: "npx",
    args: ["-y", "snyk@1.1307.4", "mcp", "-t", "stdio"],
    env: { SNYK_TOKEN: "${SNYK_TOKEN}" },
    secret_fields: ["SNYK_TOKEN"],
    env_schema: [{ key: "SNYK_TOKEN", label: "Snyk token", secret: true }],
  },
];
